server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: student
            uri:   http://localhost:8090
            predicates:
              - Path=/api/v1/students/**

          - id: school
            uri:   http://localhost:8070
            predicates:
              - Path=/api/v1/schools/**
menagment:
  tracing:
    sampling:
      probability: 1.0